### ISSUE TITLE
Hello, can you run successfully?

### ISSUE THREAD

**Issue by HAPENLY** [TRry/shadowsocks-iOS#1]

**Comment by waytc** [comment]
Yes, please follow the instructions below

1.Copy this link http://0.0.0.0:8090/proxy.pac
2.Open iOS Settings -> Wi-Fi -> i icon on the right of your connected Wi-Fi -> HTTP Proxy. Choose     Auto, paste the link in the URL field. Tap back.
3.Other apps now go through the proxy. If they don't, kill and restart them.
4.Come back every few minutes to keep Shadowsocks running in the background.

**Comment by HAPENLY** [comment]
Thank you for your answer, the project has been able to run, but cannot use the agent FQ
